CREATE TABLE wishlists (
    id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    couple_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_wl_couple FOREIGN KEY (couple_id) REFERENCES couples(id)
    ON DELETE CASCADE
);